hash-format = "sha256"

[[files]]
file = "README.md"
hash = "8b21ccd76091f2365bc3bb4e94ad6e1ddecc5ad08b29db703588bc9ec0bbf8f6"

[[files]]
file = "config/shouldersurfing-client.toml"
hash = "881e7a85519d61645e143a72e7c9ccc51cd4e84386e7eca53ce06f816e9969dc"

[[files]]
file = "mods/accessories-compat-layer.pw.toml"
hash = "c255cf4cd29718e3ab0a4c18df8bb7b626e0092c5aad7b4e67f34fc1ad4492f8"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "19cbfb37dc29169b50599dfa328fe12a0ec9caaec8ac02627b5846f3bd9d1425"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "ed45c352a49b65c7221e57d979d0c6935522dfef4968aa5b7421f4d3e670ce40"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6d3a1c92eee4dd671253c41ec000ae48064a33c45263d6adce5cad466395169d"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "9b1610cd28c49d34ce2fd760d208fb569f0e20055fee4c81ed4da6489b340312"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "992b0dca9683f225fc774d779762d18a009f2d82b9d051e7c0b55a33a95d9238"
metafile = true

[[files]]
file = "mods/cameraoverhaul.pw.toml"
hash = "4caf9367078e5565d43245e48a1f5054caf6940f0037164cf470ad0a5d093ced"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/common-network.pw.toml"
hash = "cd8078f4d044e9fb548c2b792f2f1f1c04e1b80e1479446f67de3e8687dfbf67"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "e487d315e7a44f917cd1ddc2da1b26e65968bc19fe6c0ac868dab3d2bb97bbf1"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "7cd10de618c7f46c1877d9d3e597699a7fcc02cf3982bba439ccbec95a37d0de"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "9da22561c3a5e45beb91121518a49f2e8a62bedb332574ce43a9d9b287ebc705"
metafile = true

[[files]]
file = "mods/creeper-overhaul.pw.toml"
hash = "cd4c4ec6ef26d2b61e0cb0bdd398e8d528b88ebf739fc0898bc8cb2f7a88debb"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "d10c6f194a20ef07b764bce9ef35bec526c5c5ff9acf84c53f9e172963869e56"
metafile = true

[[files]]
file = "mods/ct-overhaul-village.pw.toml"
hash = "add13c01359f4f3744d885e658bc0cd8b403a358738cb24ba6266c4e9508696b"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "8e5f6550359e71ecbea95705ec61fb03313550e6f481cabf48043929909aabae"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/deeperdarker.pw.toml"
hash = "bbb3f09fbd5a3ca7aa82c41923f4557429fa465993c2817e9966dd3f8164e318"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "b9244dca740d333c22f3425991fdd2fd40d3ae12384079a40a6fb7d4bca18a18"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d3c9b48d7caa2ed964e5d1a4dab1da5655c63f0a7e4a59231c4369be7ffc30e1"
metafile = true

[[files]]
file = "mods/enderman-overhaul.pw.toml"
hash = "1045ba1bb46eb77e2fea9be04268c2c73c161b94f3bceddbd4c3dbff1c0bf555"
metafile = true

[[files]]
file = "mods/endrem.pw.toml"
hash = "db22718a1efaf2c691cf3bdddc61b0b06bedff7cb0722aa8b1bdf4f095d116cc"
metafile = true

[[files]]
file = "mods/ends-phantasm.pw.toml"
hash = "e99bc192266affa7203e3536f96a9a584e2fb348a20d780a7c0afcb60623fa7d"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "68e0010a541dfab4ada1786114b5ac4cbd5b083519663757fcdad0a0fe186aab"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "11e43d47773d438897c9e445a1231ab2158b99ba24c7e59a6d69e62c1349b4b2"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
hash = "d93c3c494955dfc44e2590ded2ee8414d582e87f2fca00575f08576ae2197d57"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "a830f9e0393be04dd0a8a3a845b27e90cd34961887403c800e296182283d9c3e"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "3da1b263129f79811a2e675861cf3d13573e4d6bd4fe7f114b1db27bc499503e"
metafile = true

[[files]]
file = "mods/ftb-ultimine-forge.pw.toml"
hash = "bb02254ff406bc071898c14e89f3dae3230d877e5bf30b6f614fc1bbf06d9f73"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "415ae259d7d6c92717710d6f80494d9f3c0884c6a2a35f993ad31e287f64632f"
metafile = true

[[files]]
file = "mods/geophilic.pw.toml"
hash = "cdc66a084161b07f0f07e8a445272862270f1f7be71a8ec94959365395eadc86"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "dbd756dd9bb17e6ecebcf2d7052a67a2da1c7dd378bc2089bc154916080fe031"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "b8aee2057378b6f054f94550684d9a3f41ded7cc47794c8b01c107c8c2115ceb"
metafile = true

[[files]]
file = "mods/icarus.pw.toml"
hash = "cf8636013bde5684aa15276e147f8c8d7a436ca4331c6ee1f3a1257e17320111"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "b6e0a61fea06f8d6d8e1672cf07b682625c4b74efd548d5093cd9c1fed167eec"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "f1af6465928843e5a89eb0602457a89e100168053bb507150744ced4953a286e"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "33e1d182c5a166e070cc66157ec6f692ff08d8ddae975b564e69a37079b01950"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
hash = "ff76d4e6f8b16c02b3d9d0627c4a7dec766061d19cefe9bd0f1d6aee2dfade36"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "2bb3dd23b79ed5590a3534a1df937e49521613b099833f9b925687bee27d3924"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "42805ef7e224873873d190b0363f2a53dae02530553574f29fab92e258bc0470"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "98e6183c07de15c2565ee2afa70b930a877fc8d03722985f2c8137fd67da894d"
metafile = true

[[files]]
file = "mods/oh-the-biomes-weve-gone.pw.toml"
hash = "6ad737e36e7b52b0bff6440c41e7d40e528468dad5d260481b7ec082052dbc57"
metafile = true

[[files]]
file = "mods/oh-the-trees-youll-grow.pw.toml"
hash = "a50655001b949eb799fb0e4870da2ac1dc9f77511761038c8b6bce59171b8af9"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "1121ffc2012bbbf0b619a16b953d5951c41a9ef545285d01f31995b3ba6b2b8c"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "229d0e9d72e3210a98f39bd88e9cab16c5ec2e496ff3167a0bb1d074b58d7888"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "46831c04077a06df823bcd0f254833a90a9a9ccc78f5069f4b4c27fa301ac0cf"
metafile = true

[[files]]
file = "mods/philips-ruins.pw.toml"
hash = "2488bf19149e671ab9fc63823029b19ebae6c4eeabb7ff748c0be341758a246b"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "f013040d2544856ca9f8fe4e07e040aa8a78c87ace3426743a8429d73cba81a3"
metafile = true

[[files]]
file = "mods/refined-storage.pw.toml"
hash = "8e8cd2f6dcb6a46a568c13cd1ca3df0890f1389d6283ec36fc0fec20a22da057"
metafile = true

[[files]]
file = "mods/regions-unexplored.pw.toml"
hash = "1dff12e9b63565695133af67d99fedc0f92cb35387939a82f7fd11277c404847"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "27721caca5a03b743bf25888e1d984142948069dace31453f103f94f7f24d2ce"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "c0b066684294c33972d562e0cb08ea17b2d31bcf86cd1d6c63b8e968f0eac7a2"
metafile = true

[[files]]
file = "mods/shoulder-surfing-reloaded.pw.toml"
hash = "0d2e848f2d3f089f203f5e43f51bfd4a3e6fc51726e8cb242c9cb8bc7579c7e1"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "15c145ff1f48e22759871c48775951ade48bc1875b2acc9f88c23b78537c596a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "a0d7a9c8a31112c503c66e8ecf3f4d59a34de8278ff6a664bc13285a79eba54f"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "a12227faef5279cf7afbf3520aed9b23438f309ec9b39463aaf7285a84a0fc78"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "4063a3c0f2f9a6544a870f0b90679441d7333652875dafbe3db255fc67f72c82"
metafile = true

[[files]]
file = "mods/sparkweave.pw.toml"
hash = "fd2b9d3767476d9200521917dd71b8aeeba5e0e23f8160457bd864e96190d300"
metafile = true

[[files]]
file = "mods/sparsestructures.pw.toml"
hash = "8c71edbbb86e5d3e1c14ea6629382539d44e75b1061725df9c3abceb889a8591"
metafile = true

[[files]]
file = "mods/storagedrawers.pw.toml"
hash = "1d277d4c4d8f3abc49176d3b029584b70d92dcb9b89cf2cf6094e674fe9885c8"
metafile = true

[[files]]
file = "mods/structory-towers.pw.toml"
hash = "a66da60b40337e8bb57d81aef0f0c168771f2c6d8ae9d5e4af24031da2320795"
metafile = true

[[files]]
file = "mods/structory.pw.toml"
hash = "70cd30931bd186fd3f9770062dd998774ac9e1c0cf478938a62d5815ffdcfe5b"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "15962183bec2468058c70e87aa32e902a08489b0f86741088cdc9aa958ba4931"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "9bf9ab019562d204c452dd282b9a835632ffe88fdad6f20a88326da546614aaf"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
hash = "7e6948368276f2c49d5bccf52cbf80930d0daca75b4dfbc5530479f1d3f95cf8"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "02e2acc15a8c1b7bbe44a64af68574d7e024f1c45504a6997568c9fcbab3846b"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "192a4685f8a182d1fa2fae67e2fad8b74ba547726beecfe8868174b4172d76a8"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "539f362e9e192cf3b2813e0dfdfc51a5e6814129c6e82a9733842529beea6242"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "d9c0c9209bac0b693af2a7c1e47ffb28d366bad19c91df31dc6d345fa75250a1"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "634130ab233121c290fdb2567afd3939af6d98760c11f14db0426b64b8955894"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "4c2830674a08ec9f10af13e4d259aa60158bd306a3996d935e678281ec0cb5fd"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "902c397d5dfc69b497681ba71aa5b8a8a85479b1ccf25157867e4803c16dd65b"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "ee63a5958eb1e0238257e2064d917bdaf8e528a47904bdfbe04a5758a1537e9f"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "0cc13a86488cf89d2989edc1636fa63c7efa2fe819246d42af35113458d5ba5b"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "c0e40691651465b4eb1037749148c2078123604195e19b582dbef3cd5914e3b1"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "9492d0854c51570bf2a6bace6267262e7573b94c40d721348996617e5d99480a"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "1a33e6d64e88ad59b65d126c6457d582e62724167349ea184eb237435298985e"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "e2b23d0a1bf228d37ff8c3330150c24eb19cb875e113fae543191f34ded92ff8"
metafile = true
